### ISSUE TITLE
License

### ISSUE THREAD

**Issue by sam-phinizy** [stribny/sidewinder#21]
Hi there!

Nice work! Just wanted to check and see if there is a license for this project. I didn't see anything and am thinking about using it at work but didn't want to use any unlicensed code. If there isn't one could one be added? Ideally it'd be something MIT/BSD but it's your work so whatever works best for you.

**Comment by stribny** [comment]
Hi @sam-phinizy!

The project was intended to be MIT-licensed. I added the license just now.

I hope that works for you:)

**Comment by sam-phinizy** [comment]
That works great! Thanks @stribny
