### ISSUE TITLE
Use IPython debugger when a test fails

### ISSUE THREAD

**Issue by tugrulpinar** [stribny/sidewinder#25]
Django’s test framework has the `--pdb` flag to open the debugger when a test fails. This flag will automatically use `ipdb` when it’s installed.

pytest has a similar `--pdb` flag. You can configure --pdb to use the IPython debugger by setting the `--pdbcls` flag. This is most conveniently done in the addopts setting in your `pytest.ini`:

```ini
[pytest]
addopts = --pdbcls=IPython.terminal.debugger:TerminalPdb
```

**Comment by stribny** [comment]
Great idea, no reason why not to do it. Implemented here: https://github.com/stribny/sidewinder/commit/a02537d8109e823d2c20afa3536e97ff357c412d
