### ISSUE TITLE
Use github "template repository" feature 

### ISSUE THREAD

**Issue by lisad** [stribny/sidewinder#27]
ISTM that this would be cool for sidewinder though I don't know if there are any blocking problems:

https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository

Then there'd be a "Use as template" button and folks could use sidewinder as a template for starting a repository that is NOT a fork.  A person's new repository would not start with history ( though I know that's something you can wipe when cloning).  Also unlike forking it would not be setup to contribute changes back to sidewinder which is presumably a good thing when folks are going to take things in a whole new-project direction.

**Comment by stribny** [comment]
Hi @lisad,

this is an excellent idea! Honestly I didn't know about this option. I turned it on for the repo and it seems to work great.

Thanks for suggesting!

**Comment by lisad** [comment]
🎆 🥳
