### ISSUE TITLE
Jazzmin for more attractive Admin UI

### ISSUE THREAD

**Issue by tugrulpinar** [stribny/sidewinder#28]
Regular Django admin UI is a bit dull. Jazzmin is a drop-in app to make django admin site more attractive.

https://django-jazzmin.readthedocs.io/

Sometimes the Jazzmin UI changes the position of the widgets, search and filter fields etc (some may not prefer that). So I think I'd be a good idea to make it optional.

I would add to the `.env` file:

`JAZZMIN_ADMIN_UI=0`

```python
JAZZMIN_ADMIN_UI = env.bool("JAZZMIN_ADMIN_UI")

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.flatpages",
    "django.forms",
    "django_extensions",
    "allauth",
    "allauth.account",
    "rest_framework",
    "rest_framework.authtoken",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    "drf_standardized_errors",
    "corsheaders",
    "django_htmx",
    "huey.contrib.djhuey",
    "bx_django_utils",
    "huey_monitor",
    "tennisbuddy.core",
]

if JAZZMIN_ADMIN_UI:
    INSTALLED_APPS.insert(0, "jazzmin")
```

**Comment by stribny** [comment]
I have to be honest that I don't like Jazzmin, I think it looks *worse* than native Django admin. The best contender for me would be https://github.com/unfoldadmin/django-unfold.

That being said I am not sure about including this in Sidewinder which is focused more on the development experience and deployment, as everyone will have different UI preferences, as demonstrated here :)
