### ISSUE TITLE
Python version 3.10

### ISSUE THREAD

**Issue by c0x65o** [stribny/sidewinder#7]
Is version 3.10 of python required? Is it okay to update the `pyproject.toml` to drop back to 3.9?

**Comment by stribny** [comment]
I will think about it, it is true there might not be a requirement for >3.9 regarding the dependencies and the little bit of code.

If you run on 3.9, can you confirm that it works for you?

**Comment by c0x65o** [comment]
I changed it to version 3.9, and it all works, but this is the first time I have used this code.

**Comment by stribny** [comment]
Cool!

I will probably put it back to 3.9 once I get back to make some changes here. Thanks for trying it out and sharing your thoughts!

**Comment by c0x65o** [comment]
Not sure if this is related or a different issue, but when I run pytest in the poetry shell I get the following error: "ModuleNotFoundError: No module named 'importlib_metadata". This is my first time using poetry.

poetry.lock:min-versions = ["babel (==2.9.0)", "click (==7.0)", "colorama (==0.4)", "ghp-import (==1.0)", "importlib-metadata (==4.3)", "jinja2 (==2.11.1)", "markdown (==3.2.1)", "markupsafe (==2.0.1)", "mergedeep (==1.3.4)", "packaging (==20.5)", "pyyaml (==5.1)", "pyyaml-env-tag (==0.1)", "typing-extensions (==3.10)", "watchdog (==2.0)"]
poetry.lock:plugins = ["importlib-metadata"]

**Comment by stribny** [comment]
Can you try to run `poetry lock --no-update` to re-generate the lock file?

**Comment by c0x65o** [comment]
That did not correct the issue. 

I did a pip install importlib_metadata and it seems to correct it.

**Comment by stribny** [comment]
I reverted the required Python version to 3.9. Also, I updated `isort` since the old version caused problems with new Poetry. So if you have latest Poetry installed and run the `poetry install` to create a fresh environment, everything should work for you.
